<?php

namespace Proxies\__CG__\Tonicmanager\AppBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Client extends \Tonicmanager\AppBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNom($nom)
    {
        $this->__load();
        return parent::setNom($nom);
    }

    public function getNom()
    {
        $this->__load();
        return parent::getNom();
    }

    public function setPrenom($prenom)
    {
        $this->__load();
        return parent::setPrenom($prenom);
    }

    public function getPrenom()
    {
        $this->__load();
        return parent::getPrenom();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setDateNaissance($dateNaissance)
    {
        $this->__load();
        return parent::setDateNaissance($dateNaissance);
    }

    public function getDateNaissance()
    {
        $this->__load();
        return parent::getDateNaissance();
    }

    public function setAdresse($adresse)
    {
        $this->__load();
        return parent::setAdresse($adresse);
    }

    public function getAdresse()
    {
        $this->__load();
        return parent::getAdresse();
    }

    public function setVille($ville)
    {
        $this->__load();
        return parent::setVille($ville);
    }

    public function getVille()
    {
        $this->__load();
        return parent::getVille();
    }

    public function setCp($cp)
    {
        $this->__load();
        return parent::setCp($cp);
    }

    public function getCp()
    {
        $this->__load();
        return parent::getCp();
    }

    public function setPhoto($photo)
    {
        $this->__load();
        return parent::setPhoto($photo);
    }

    public function getPhoto()
    {
        $this->__load();
        return parent::getPhoto();
    }

    public function upload()
    {
        $this->__load();
        return parent::upload();
    }

    public function getUploadDir()
    {
        $this->__load();
        return parent::getUploadDir();
    }

    public function setTelephone($telephone)
    {
        $this->__load();
        return parent::setTelephone($telephone);
    }

    public function getTelephone()
    {
        $this->__load();
        return parent::getTelephone();
    }

    public function setPortable($portable)
    {
        $this->__load();
        return parent::setPortable($portable);
    }

    public function getPortable()
    {
        $this->__load();
        return parent::getPortable();
    }

    public function setLieuNaissance($lieuNaissance)
    {
        $this->__load();
        return parent::setLieuNaissance($lieuNaissance);
    }

    public function getLieuNaissance()
    {
        $this->__load();
        return parent::getLieuNaissance();
    }

    public function setCivilite($civilite)
    {
        $this->__load();
        return parent::setCivilite($civilite);
    }

    public function getCivilite()
    {
        $this->__load();
        return parent::getCivilite();
    }

    public function setProspect($prospect)
    {
        $this->__load();
        return parent::setProspect($prospect);
    }

    public function getProspect()
    {
        $this->__load();
        return parent::getProspect();
    }

    public function setDateProspect($dateProspect)
    {
        $this->__load();
        return parent::setDateProspect($dateProspect);
    }

    public function getDateProspect()
    {
        $this->__load();
        return parent::getDateProspect();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'civilite', 'nom', 'prenom', 'email', 'telephone', 'portable', 'dateNaissance', 'lieuNaissance', 'adresse', 'ville', 'cp', 'photo', 'prospect', 'dateProspect');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}