<?php

namespace Tonicmanager\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FrequentationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrequentationRepository extends EntityRepository
{
}
