<?php

namespace Tonicmanager\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SuppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuppRepository extends EntityRepository
{
}
