# src/Sdz/BlogBundle/Resources/config/routing.yml
tonicmanagerAppBundle_homepage:
    path: /
    defaults: { _controller: TonicmanagerAppBundle:Default:index }
tonicmanagerAppBundle_admin:
    path: /dashboard
    defaults: { _controller: TonicmanagerAppBundle:Default:dashboard }
tonicmanagerAppBundle_scanClient:
    path: /scanCarte
    defaults: { _controller: TonicmanagerAppBundle:Default:scanCarte }
tonicmanagerAppBundle_rechercheClient:
    path: /rechercheClient
    defaults: { _controller: TonicmanagerAppBundle:Default:rechercheClient }
tonicmanagerAppBundle_consultation:
    path: /ConsultationClient
    defaults: { _controller: TonicmanagerAppBundle:Default:consultation }
tonicmanagerAppBundle_ajoutClient:
    path: /nouveauClient
    defaults: { _controller: TonicmanagerAppBundle:Client:ajout }
tonicmanagerAppBundle_listeClient:
    path: /listeClient
    defaults: { _controller: TonicmanagerAppBundle:Client:liste }
tonicmanagerAppBundle_ajoutAbonnement:
    path: /ajoutAbonnement
    defaults: { _controller: TonicmanagerAppBundle:Abonnement:ajout }
tonicmanagerAppBundle_listeAbonnement:
    path: /listeAbonnement
    defaults: { _controller: TonicmanagerAppBundle:Abonnement:liste }
tonicmanagerAppBundle_ajoutOption:
    path: /ajoutOption
    defaults: { _controller: TonicmanagerAppBundle:Supp:ajout }
tonicmanagerAppBundle_listeOption:
    path: /listeOption
    defaults: { _controller: TonicmanagerAppBundle:Supp:liste }
tonicmanagerAppBundle_ajoutContrat:
    path: /ajoutContrat
    defaults: { _controller: TonicmanagerAppBundle:Contrat:ajout }
tonicmanagerAppBundle_ficheContrat:
    path: /ficheContrat/{idClient}
    defaults: { _controller: TonicmanagerAppBundle:Contrat:fiche }
tonicmanagerAppBundle_editContrat:
    path: /editContrat/{idContrat}
    defaults: { _controller: TonicmanagerAppBundle:Contrat:edit }

